-- {{{ Plugins

lvim.plugins = {
  "aklt/plantuml-syntax",
  "christoomey/vim-tmux-navigator",
  "christoomey/vim-tmux-runner",
  "dkarter/bullets.vim",
  "f3fora/cmp-spell",
  "hrsh7th/cmp-calc",
  "hrsh7th/cmp-cmdline",
  "junegunn/fzf",
  "junegunn/fzf.vim",
  "junegunn/vim-easy-align",
  "kovetskiy/sxhkd-vim",
  "kylechui/nvim-surround",
  "lervag/vimtex",
  "lervag/wiki-ft.vim",
  "lervag/wiki.vim",
  "lunarvim/colorschemes",
  "mechatroner/rainbow_csv",
  "tpope/vim-bundler",
  "tpope/vim-characterize",
  "tpope/vim-commentary",
  "tpope/vim-dispatch",
  "tpope/vim-endwise",
  "tpope/vim-fugitive",
  "tpope/vim-rails",
  "tpope/vim-repeat",
  "tpope/vim-unimpaired",
  "triglav/vim-visual-increment",
  "tweekmonster/startuptime.vim",
  "vim-utils/vim-most-minimal-folds",
  "xiyaowong/nvim-transparent",
  "RRethy/nvim-base16",
  "Traap/vim-bundle-abbreviate",
  "Traap/vim-bundle-autocmd",
  "Traap/vim-bundle-fzf",
  "Traap/vim-bundle-plantuml",
  "Traap/vim-bundle-rainbow",
  "Traap/vim-bundle-tmux-runner",
  "Traap/vim-bundle-vimtex",
  "Traap/vim-bundle-vimwiki",
}

-- ------------------------------------------------------------------------- }}}
