-- {{{ Plugins

lvim.plugins = {
  'NvChad/nvim-colorizer.lua',
  'aklt/plantuml-syntax',
  'christoomey/vim-tmux-navigator',
  'christoomey/vim-tmux-runner',
  'dkarter/bullets.vim',
  'f3fora/cmp-spell',
  'hrsh7th/cmp-calc',
  'hrsh7th/cmp-cmdline',
  'junegunn/fzf',
  'junegunn/fzf.vim',
  'junegunn/vim-easy-align',
  'kovetskiy/sxhkd-vim',
  'kylechui/nvim-surround',
  'lervag/vimtex',
  'lervag/wiki-ft.vim',
  'lervag/wiki.vim',
  'lunarvim/colorschemes',
  'mechatroner/rainbow_csv',
  'moll/vim-bbye',
  'nvim-telescope/telescope-media-files.nvim',
  'olexsmir/gopher.nvim',
  'tpope/gem-browse',
  'tpope/vim-bundler',
  'tpope/vim-characterize',
  'tpope/vim-commentary',
  'tpope/vim-dispatch',
  'tpope/vim-endwise',
  'tpope/vim-eunuch',
  'tpope/vim-fugitive',
  'tpope/vim-projectionist',
  'tpope/vim-rails',
  'tpope/vim-rake',
  'tpope/vim-rbenv',
  'tpope/vim-repeat',
  -- 'tpope/vim-surround',
  'tpope/vim-unimpaired',
  'tpope/vim-vinegar',
  'triglav/vim-visual-increment',
  'tweekmonster/startuptime.vim',
  'vim-utils/vim-most-minimal-folds',
  'xiyaowong/nvim-transparent',
  'ChristianChiarulli/nvim-ts-rainbow',
  'RRethy/nvim-base16',
  'ThePrimeagen/harpoon',
  'Traap/vim-bundle-abbreviate',
  'Traap/vim-bundle-fzf',
  'Traap/vim-bundle-plantuml',
  'Traap/vim-bundle-tmux-runner',
  'Traap/vim-bundle-vimtex',
  'Traap/vim-bundle-vimwiki',
  -- dap
  'jose-elias-alvarez/typescript.nvim',
  'mfussenegger/nvim-dap-python',
  'mxsdev/nvim-dap-vscode-js',
  'leoluz/nvim-dap-go',
  'theHamsta/nvim-dap-virtual-text',
}
-- ------------------------------------------------------------------------- }}}
